### ISSUE TITLE
Add a conda-forge build of cunit for Windows

### ISSUE THREAD

**Issue by wolfv** [RoboStack/ros-foxy#1]
We could use this vcpkg cmake file: https://github.com/microsoft/vcpkg/blob/master/ports/cunit/CMakeLists.txt

**Comment by Tobias-Fischer** [comment]
Seems like you've had this idea years ago ;): https://github.com/conda-forge/cunit-feedstock/pull/7

**Comment by wolfv** [comment]
hehe, yeah, I also realized that shortly after :see_no_evil:

**Comment by songyuc** [comment]
Following this issue.

**Comment by Tobias-Fischer** [comment]
Done - https://github.com/conda-forge/cunit-feedstock/pull/10
